language: java

sudo: required

cache:
  directories:
    - ~/.m2

jdk:
- oraclejdk8

env:
  matrix:
  - COMMI=b007b22e
  - COMMI=efef09b0

before_script:
- git clone https://github.com/Spirals-Team/maven-repair
- cd maven-repair
- mvn install

script:
- cd /home/travis/build/plarentih/repairBugsJar/script
- python bugs-dot-jar.py checkout -p accumulo -i $COMMI
- cd /home/travis/build/plarentih/repairBugsJar/bugs/accumulo/$COMMI
- mvn -X fr.inria.gforge.spirals:repair-maven-plugin:nopol
- d=/home/travis/build/plarentih/repairBugsJar/results/accumulo/$COMMI/nopol
- test -d $d || mkdir -p $d && cp -Rf /home/travis/build/plarentih/repairBugsJar/bugs/accumulo/$COMMI/target/nopol/output.json $d
- git add /home/travis/build/plarentih/repairBugsJar/results/accumulo/$COMMI/nopol/output.json
- git commit -m "results for bug commit $COMMI"
- git pull --rebase
- git push
- cd /home/travis/build/plarentih/repairBugsJar
